### ISSUE TITLE
Add support for files larger that 32MB

### ISSUE THREAD

**Issue by TheSandBoxMKG** [julienc91/multidl#6]
It crashes when trying to download something bigger than 32MB.

I can upload some Luma3DS dumps if you need.

**Comment by julienc91** [comment]
@TheSandBoxMKG Hi! Can you specify from which type of source you're trying to download from (http, ftp, ...), and the full error message you get?

**Comment by TheSandBoxMKG** [comment]
Yes, it's an HTTP source (An to be honest beforehand, it's one of those not so legal sites ^_^" but I don't think that's relevant to the issue in question)

Here you have the video some milliseconds before it crashes (it was under 32MB, I thought it would crash later but it's still around there), an image of the Luma3DS error screen and the dump Luma3DS did.

http://download4.erista.me/content/165?token=7187047ddc25bffb0b455ca3ac875d77

**Comment by TheSandBoxMKG** [comment]
Wait, wrong project, I'm closing this issue. (There's another project also named MultiDL)

I'm sorry.
